# Generated by Django 3.0.4 on 2020-04-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200405_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(default='06.04.2020'),
        ),
    ]
