# Generated by Django 3.0.4 on 2020-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20200406_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=200),
        ),
    ]
